language: python

python:
  - "3.5"

install:
  - ./bin/build
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py import rabobank-csv ./examples/rabobank.csv


